[[redirects]]
  from = "/about"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/services"
  to = "/"
  status = 200
  force = true

 [[redirects]]
   from = "/watchterminal/privacy"
   to = "/"
   status = 200
   force = true

[functions]
  directory = "functions"